### ISSUE TITLE
wok encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [robatron/robmd.net#16]
(dev) root@localhost:/usr/local/wok-site/robmd.net# wok
Traceback (most recent call last):
  File "/root/dev/bin/wok", line 4, in <module>
    __import__('pkg_resources').run_script('wok==1.1.1', 'wok')
  File "/root/dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/root/dev/lib/python2.7/site-packages/wok-1.1.1-py2.7.egg/EGG-INFO/scripts/wok", line 4, in <module>
    
  File "build/bdist.linux-x86_64/egg/wok/engine.py", line 152, in __init__
  File "build/bdist.linux-x86_64/egg/wok/engine.py", line 189, in generate_site
  File "build/bdist.linux-x86_64/egg/wok/engine.py", line 347, in prepare_output
  File "build/bdist.linux-x86_64/egg/wok/engine.py", line 302, in run_hook
TypeError: compile() takes exactly 1 argument (2 given)
(dev) root@localhost:/usr/local/wok-site/robmd.net#

**Comment by robatron** [comment]
Hi there, @luckypoem. This repository contains the source files for an old personal website of mine, and is no longer maintained. You may want to check out the [wok](https://github.com/mythmon/wok) repository if you're interested in creating your own site.
